
# EXTRA_CFLAGS += -fplugin=/path/to/container/dir/adelie-source/source-main/gcc-plugins/fix_relocations_plugin.so
# EXTRA_CFLAGS += -fplugin=/path/to/container/dir/adelie-source/source-main/gcc-plugins/function_proepilogue_plugin.so
# EXTRA_CFLAGS += -fplugin=/path/to/container/dir/adelie-source/source-main/gcc-plugins/rerandomization_wrapper_plugin.so

obj-$(CONFIG_RANDOM_TEST_DRIVER) += random_test_driver.o